name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

env:
  EC2_HOST: 18.204.15.151
  EC2_USER: ubuntu

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/blog-key.pem
          chmod 600 ~/.ssh/blog-key.pem
          ssh-keyscan -H ${{ env.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/blog-key.pem ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
            cd ~/blog2
            git pull origin main
            cd backend
            npm install
            npm run build
            npx prisma generate
            npx prisma migrate deploy
            sudo systemctl restart blog-backend
            sudo systemctl status blog-backend --no-pager
          EOF

      - name: Verify deployment
        run: |
          sleep 5
          curl -f https://api.stevewanglog.com/health || exit 1
